# Ethereal-Theme (Windows 7)
foreground #d1dfeb
background #0a111a
selection_foreground #d1dfeb
selection_background #182d42
cursor #59b2ff
cursor_text_color #0a111a
color0 #0a111a
color1 #ff7878
color2 #6ce89f
color3 #ffffff
color4 #ffd166
color5 #59b2ff
color6 #ffd166
color7 #d1dfeb
color8 #4f657a
color9 #ff7878
color10 #6ce89f
color11 #ffa8cc
color12 #ffd166
color13 #59b2ff
color14 #ffd166
color15 #ffffff
