# Ethereal-Theme (Kerubin)
foreground #eae6f5
background #161420
selection_foreground #eae6f5
selection_background #463a46
cursor #ffb3d1
cursor_text_color #161420
color0 #161420
color1 #ff7096
color2 #c3ffd8
color3 #ffe5ad
color4 #a2d2ff
color5 #ffb3d1
color6 #c2f0fc
color7 #eae6f5
color8 #6b6380
color9 #ff7096
color10 #c3ffd8
color11 #ffd6a5
color12 #ffa8cc
color13 #dec9ff
color14 #c2f0fc
color15 #ffffff
