# Ethereal-Theme (Luminous Space)
foreground #e0ddf5
background #0d0b1a
selection_foreground #e0ddf5
selection_background #0b363a
cursor #00ffd2
cursor_text_color #0d0b1a
color0 #0d0b1a
color1 #ff9de0
color2 #ffffff
color3 #bfdbfe
color4 #00ffd2
color5 #00ffd2
color6 #00ffd2
color7 #e0ddf5
color8 #6c698f
color9 #ff9de0
color10 #ffffff
color11 #ff9de0
color12 #3cffdc
color13 #cf9dff
color14 #00ffd2
color15 #ffffff
