# Ethereal-Theme (Frutiger)
foreground #d0e6f0
background #08131a
selection_foreground #d0e6f0
selection_background #07322d
cursor #00ffaa
cursor_text_color #08131a
color0 #08131a
color1 #ff7096
color2 #00ffaa
color3 #f0fdf4
color4 #00f0ff
color5 #00ffaa
color6 #00f0ff
color7 #d0e6f0
color8 #49697a
color9 #ff7096
color10 #00ffaa
color11 #fff080
color12 #00d2ff
color13 #00d2ff
color14 #00f0ff
color15 #ffffff
