# Ethereal-Theme (Angelical Light)
foreground #3f344a
background #fffaf3
selection_foreground #3f344a
selection_background #f6e2e3
cursor #9f4a70
cursor_text_color #fffaf3
color0 #f4eadf
color1 #c93662
color2 #267c52
color3 #8a6a18
color4 #2f77b4
color5 #9f4a70
color6 #23748f
color7 #3f344a
color8 #746684
color9 #c93662
color10 #267c52
color11 #9b5b13
color12 #b13d6e
color13 #7d5fb2
color14 #23748f
color15 #ffffff
