# Ethereal-Theme (Gothic Angel)
foreground #eae3e7
background #0f090b
selection_foreground #eae3e7
selection_background #39121d
cursor #ff3b70
cursor_text_color #0f090b
color0 #0f090b
color1 #ff3b70
color2 #ffffff
color3 #e8c4d0
color4 #e8c4d0
color5 #ff3b70
color6 #ff3b70
color7 #eae3e7
color8 #664e56
color9 #ff3b70
color10 #ffffff
color11 #ff7da0
color12 #ff5c86
color13 #ff3b70
color14 #ff3b70
color15 #ffffff
