# Ethereal-Theme (Y2K Aero)
foreground #c8d6e5
background #0b1720
selection_foreground #c8d6e5
selection_background #093d47
cursor #00f0ff
cursor_text_color #0b1720
color0 #0b1720
color1 #ff7096
color2 #ffffff
color3 #a5f3fc
color4 #00f0ff
color5 #00f0ff
color6 #00f0ff
color7 #c8d6e5
color8 #4f6277
color9 #ff7096
color10 #ffffff
color11 #ffd166
color12 #00f0ff
color13 #00d2ff
color14 #00f0ff
color15 #ffffff
