# Ethereal-Theme (Dreamscape)
foreground #f4effc
background #141026
selection_foreground #f4effc
selection_background #3d2b43
cursor #ffabcc
cursor_text_color #141026
color0 #141026
color1 #ff7096
color2 #baffec
color3 #89ddff
color4 #ffabcc
color5 #ffabcc
color6 #ffabcc
color7 #f4effc
color8 #7d729c
color9 #ff7096
color10 #baffec
color11 #ff7096
color12 #ffccd9
color13 #ffcbba
color14 #ffabcc
color15 #ffffff
