# Ethereal-Theme (Default)
foreground #eae6f5
background #07080c
selection_foreground #eae6f5
selection_background #212c37
cursor #9cd2ff
cursor_text_color #07080c
color0 #07080c
color1 #ff7096
color2 #a7f3d0
color3 #82aaff
color4 #89ddff
color5 #9cd2ff
color6 #89ddff
color7 #eae6f5
color8 #576275
color9 #ff7096
color10 #a7f3d0
color11 #ffa8cc
color12 #7ec2ff
color13 #dec9ff
color14 #89ddff
color15 #ffffff
