# Ethereal-Theme (Aurora)
foreground #e2ecef
background #060c0e
selection_foreground #e2ecef
selection_background #053730
cursor #00ffcc
cursor_text_color #060c0e
color0 #060c0e
color1 #ff7096
color2 #8effd8
color3 #82aaff
color4 #00ffcc
color5 #00ffcc
color6 #00ffcc
color7 #e2ecef
color8 #5b757c
color9 #ff7096
color10 #8effd8
color11 #ff7096
color12 #5cffe2
color13 #d1a3ff
color14 #00ffcc
color15 #ffffff
