# Ethereal-Theme (Cathedral)
foreground #eaeaf2
background #0d0d12
selection_foreground #eaeaf2
selection_background #15223a
cursor #3b82f6
cursor_text_color #0d0d12
color0 #0d0d12
color1 #ef4444
color2 #10b981
color3 #8b5cf6
color4 #3b82f6
color5 #3b82f6
color6 #3b82f6
color7 #eaeaf2
color8 #606073
color9 #ef4444
color10 #10b981
color11 #ef4444
color12 #60a5fa
color13 #ef4444
color14 #3b82f6
color15 #ffffff
