# Ethereal-Theme (Moonlit)
foreground #e6ebf5
background #0a0d14
selection_foreground #e6ebf5
selection_background #25303d
cursor #a5d6ff
cursor_text_color #0a0d14
color0 #0a0d14
color1 #ff7096
color2 #a5f3ff
color3 #89ddff
color4 #a5d6ff
color5 #a5d6ff
color6 #a5d6ff
color7 #e6ebf5
color8 #6a768c
color9 #ff7096
color10 #a5f3ff
color11 #ff7096
color12 #cbe5ff
color13 #d2ccff
color14 #a5d6ff
color15 #ffffff
