# Ethereal-Theme (Seraphim)
foreground #f4eae0
background #0e0c0a
selection_foreground #f4eae0
selection_background #393008
cursor #ffd700
cursor_text_color #0e0c0a
color0 #0e0c0a
color1 #ff7675
color2 #ffe599
color3 #e38e65
color4 #ffd700
color5 #ffd700
color6 #ffd700
color7 #f4eae0
color8 #8a7b75
color9 #ff7675
color10 #ffe599
color11 #ff7675
color12 #ffe57f
color13 #ffab91
color14 #ffd700
color15 #ffffff
