# Ethereal-Theme (Y2K Aero)
[colors.primary]
background = "#0b1720"
foreground = "#c8d6e5"

[colors.cursor]
text = "#0b1720"
cursor = "#00f0ff"

[colors.selection]
text = "#c8d6e5"
background = "#093d47"

[colors.normal]
black = "#0b1720"
red = "#ff7096"
green = "#ffffff"
yellow = "#a5f3fc"
blue = "#00f0ff"
magenta = "#00f0ff"
cyan = "#00f0ff"
white = "#c8d6e5"

[colors.bright]
black = "#4f6277"
red = "#ff7096"
green = "#ffffff"
yellow = "#ffd166"
blue = "#00f0ff"
magenta = "#00d2ff"
cyan = "#00f0ff"
white = "#ffffff"
